"""
Observatory — Evaluation Framework: AWS infrastructure.

Topology: an ALB in front of one Fargate task, Postgres on RDS, and an EFS
volume for the two things that must outlive a task — uploaded documents and the
ChromaDB index. Secrets come from Secrets Manager and are injected as
environment variables; nothing sensitive is baked into the image or this file.

READ BEFORE SCALING. `desired_count` is 1 on purpose, and raising it is not a
config tweak:

  * ChromaDB's PersistentClient is SQLite on disk. Several tasks writing one
    SQLite file over NFS is a corruption risk — NFS lock semantics are not what
    SQLite assumes. Two tasks are not twice the throughput; they are a data
    hazard.
  * The BM25 index and the retrieval bundle are cached in-process
    (_INDEX_CACHE in rag_evaluator.py). A second task shares none of it and
    re-chunks every document on its first request.

To scale past one task, move Chroma to a server deployment (or swap the vector
store for OpenSearch/pgvector) and make BM25 shared. Until then, one task is
the correct answer, and this is an internal evaluation tool whose load is a
handful of analysts.
"""
from aws_cdk import (
    Stack, Duration, RemovalPolicy, CfnOutput,
    aws_ec2 as ec2,
    aws_ecs as ecs,
    aws_ecs_patterns as ecs_patterns,
    aws_efs as efs,
    aws_rds as rds,
    aws_logs as logs,
    aws_secretsmanager as secretsmanager,
)
from constructs import Construct


class ObservatoryStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # ── Network ───────────────────────────────────────────────────────
        # One NAT gateway rather than one per AZ: the task needs egress to
        # Groq and HuggingFace, but this is not a high-availability service,
        # and a second NAT would roughly double the fixed monthly cost for no
        # benefit at a single task.
        vpc = ec2.Vpc(
            self, "Vpc",
            max_azs=2,
            nat_gateways=1,
        )

        # ── Application secrets ───────────────────────────────────────────
        # Created EMPTY. Fill it in after the first deploy (see DEPLOY.md) —
        # putting real keys in CDK source would commit them to a public repo,
        # which is the exact failure this stack is built to avoid.
        app_secret = secretsmanager.Secret(
            self, "AppSecrets",
            secret_name="observatory/app",
            description="Groq keys and optional integrations for Observatory",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template='{"GROQ_API_KEY":"","GROQ_API_KEY_2":"",'
                                       '"LANGCHAIN_API_KEY":"","COLLINEAR_API_KEY":""}',
                generate_string_key="placeholder",
            ),
        )

        # ── Database ──────────────────────────────────────────────────────
        # Credentials are generated by RDS and stored in Secrets Manager; they
        # never appear in this file or in the task definition in plaintext.
        db = rds.DatabaseInstance(
            self, "Database",
            engine=rds.DatabaseInstanceEngine.postgres(
                version=rds.PostgresEngineVersion.VER_16_4
            ),
            instance_type=ec2.InstanceType.of(
                ec2.InstanceClass.BURSTABLE4_GRAVITON, ec2.InstanceSize.SMALL
            ),
            vpc=vpc,
            vpc_subnets=ec2.SubnetSelection(
                subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS
            ),
            credentials=rds.Credentials.from_generated_secret("observatory"),
            database_name="rag_eval",
            allocated_storage=20,
            max_allocated_storage=100,
            backup_retention=Duration.days(7),
            deletion_protection=True,
            removal_policy=RemovalPolicy.SNAPSHOT,
            storage_encrypted=True,
        )

        # ── Shared filesystem ─────────────────────────────────────────────
        # Uploaded documents and the Chroma index. Both must survive a task
        # replacement: uploads are user data that cannot be regenerated, and
        # rebuilding the index means re-embedding every document.
        file_system = efs.FileSystem(
            self, "DataFs",
            vpc=vpc,
            encrypted=True,
            lifecycle_policy=efs.LifecyclePolicy.AFTER_30_DAYS,
            performance_mode=efs.PerformanceMode.GENERAL_PURPOSE,
            removal_policy=RemovalPolicy.RETAIN,
        )
        access_point = file_system.add_access_point(
            "DataAccessPoint",
            path="/observatory",
            create_acl=efs.Acl(owner_uid="10001", owner_gid="10001", permissions="755"),
            posix_user=efs.PosixUser(uid="10001", gid="10001"),
        )

        cluster = ecs.Cluster(
            self, "Cluster", vpc=vpc,
            container_insights_v2=ecs.ContainerInsights.ENABLED,
        )

        # ── Task definition ───────────────────────────────────────────────
        # 2 vCPU / 8GB: embedding and reranking run on CPU via onnxruntime, and
        # the ONNX models plus a loaded index are memory-hungry. Under-sizing
        # shows up as request timeouts during indexing, not as a clean error.
        task_definition = ecs.FargateTaskDefinition(
            self, "TaskDef",
            cpu=2048,
            memory_limit_mib=8192,
            runtime_platform=ecs.RuntimePlatform(
                cpu_architecture=ecs.CpuArchitecture.X86_64,
                operating_system_family=ecs.OperatingSystemFamily.LINUX,
            ),
        )

        task_definition.add_volume(
            name="data",
            efs_volume_configuration=ecs.EfsVolumeConfiguration(
                file_system_id=file_system.file_system_id,
                transit_encryption="ENABLED",
                authorization_config=ecs.AuthorizationConfig(
                    access_point_id=access_point.access_point_id,
                    iam="ENABLED",
                ),
            ),
        )

        container = task_definition.add_container(
            "app",
            # Builds the Dockerfile in the parent directory and pushes it to
            # ECR as part of `cdk deploy`. Requires Docker running locally.
            image=ecs.ContainerImage.from_asset(".."),
            logging=ecs.LogDriver.aws_logs(
                stream_prefix="observatory",
                log_retention=logs.RetentionDays.ONE_MONTH,
            ),
            environment={
                "UPLOAD_DIR": "/data/uploads",
                "RAG_INDEX_CACHE_DIR": "/data/index",
                "GROQ_MODEL": "openai/gpt-oss-120b",
                "DEEPEVAL_MODEL": "openai/gpt-oss-120b",
                "DEEPEVAL_MODEL_FALLBACKS": "qwen/qwen3.6-27b,openai/gpt-oss-20b",
                "LANGCHAIN_PROJECT": "observatory-eval",
            },
            secrets={
                # The RDS-managed secret stores connection details as SEPARATE
                # JSON keys and contains no assembled URL — there is no "uri"
                # field to reference. The parts are injected individually and
                # database.py builds the URL from them, which also keeps the
                # password out of any plaintext environment variable.
                "DB_HOST": ecs.Secret.from_secrets_manager(db.secret, "host"),
                "DB_PORT": ecs.Secret.from_secrets_manager(db.secret, "port"),
                "DB_NAME": ecs.Secret.from_secrets_manager(db.secret, "dbname"),
                "DB_USER": ecs.Secret.from_secrets_manager(db.secret, "username"),
                "DB_PASSWORD": ecs.Secret.from_secrets_manager(db.secret, "password"),
                "GROQ_API_KEY": ecs.Secret.from_secrets_manager(app_secret, "GROQ_API_KEY"),
                "GROQ_API_KEY_2": ecs.Secret.from_secrets_manager(app_secret, "GROQ_API_KEY_2"),
                "LANGCHAIN_API_KEY": ecs.Secret.from_secrets_manager(app_secret, "LANGCHAIN_API_KEY"),
                "COLLINEAR_API_KEY": ecs.Secret.from_secrets_manager(app_secret, "COLLINEAR_API_KEY"),
            },
            port_mappings=[ecs.PortMapping(container_port=8000)],
        )
        container.add_mount_points(
            ecs.MountPoint(container_path="/data", source_volume="data", read_only=False)
        )

        # ── Service + load balancer ───────────────────────────────────────
        service = ecs_patterns.ApplicationLoadBalancedFargateService(
            self, "Service",
            cluster=cluster,
            task_definition=task_definition,
            desired_count=1,            # see the module docstring before raising
            public_load_balancer=True,
            assign_public_ip=False,
            task_subnets=ec2.SubnetSelection(
                subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS
            ),
            # The app runs create_all() and safe_migrate() at import, then loads
            # ONNX models, so first boot is slow. Too short a grace period makes
            # ECS kill the task mid-startup and retry forever.
            health_check_grace_period=Duration.seconds(180),
            circuit_breaker=ecs.DeploymentCircuitBreaker(rollback=True),
        )

        service.target_group.configure_health_check(
            path="/healthz",
            healthy_threshold_count=2,
            unhealthy_threshold_count=5,
            interval=Duration.seconds(30),
            timeout=Duration.seconds(10),
        )
        # An evaluation run is long. The default 60s idle timeout would cut the
        # connection while a run is still legitimately working.
        service.load_balancer.set_attribute("idle_timeout.timeout_seconds", "300")

        # Deregistration delay defaults to 300s; a single-task service has no
        # second task to drain to, so waiting the full five minutes only makes
        # deploys slower.
        service.target_group.set_attribute("deregistration_delay.timeout_seconds", "30")

        db.connections.allow_default_port_from(service.service, "Fargate task to Postgres")
        file_system.connections.allow_default_port_from(service.service, "Fargate task to EFS")

        CfnOutput(self, "ServiceUrl", value=f"http://{service.load_balancer.load_balancer_dns_name}")
        CfnOutput(self, "AppSecretName", value=app_secret.secret_name)
        CfnOutput(self, "DbSecretName", value=db.secret.secret_name if db.secret else "n/a")
