"""Conversational routing — deciding small talk vs. a documentation question.

The RAG pipeline answers questions *about the documentation*. But Buddy is a
copilot, so it also has to hold a conversation: greet the user, say who it is
and what it can do, respond to "how are you", thanks, and goodbyes.

This module's only job is **classification**: given a message, decide whether
it's small talk (and which kind), or a real documentation question that should
go to retrieval. It deliberately does *not* write the reply — small-talk replies
are generated by the LLM (see :meth:`app.rag.llm.LLMClient.chat`) so Buddy sounds
natural and varied instead of repeating a fixed string.

Keeping the *routing* deterministic (regex, ~0ms, no API call) means we never
waste a retrieval on "hi", and never let the LLM answer a documentation question
without grounded context.
"""

from __future__ import annotations

import re
from enum import Enum

ASSISTANT_NAME = "Buddy"


class Intent(str, Enum):
    """Conversational (non-document) intents Buddy handles as small talk."""

    GREETING = "greeting"
    WELLBEING = "wellbeing"
    IDENTITY = "identity"
    CAPABILITIES = "capabilities"
    THANKS = "thanks"
    GOODBYE = "goodbye"


# Intent detection. Patterns are matched against the lower-cased, stripped
# message. Order matters: the first pattern that matches wins, so more specific
# intents (wellbeing/identity/capabilities) are checked before a bare greeting.
_INTENT_PATTERNS: list[tuple[Intent, re.Pattern[str]]] = [
    (
        # "how are you" and its many shorthands. Checked before capabilities/
        # identity so it isn't mistaken for "how can you help".
        Intent.WELLBEING,
        re.compile(
            r"\b(how (are|r|'?re) (you|u|ya|yah)|how'?s it going|"
            r"how are things|how do you do|how (have|'?ve) you been|"
            r"hope you'?re (well|good)|"
            r"(you|u) (doing )?(ok|okay|good|well|alright|fine))\b"
        ),
    ),
    (
        Intent.IDENTITY,
        re.compile(
            r"\b(who (are|r) (you|u)|what (are|r) (you|u)|"
            r"(your|ur) name|what'?s (your|ur) name|"
            r"who am i (talking|chatting|speaking) to|who made you|"
            r"are you (a )?(bot|ai|human|chatgpt|robot|real|person))\b"
        ),
    ),
    (
        Intent.CAPABILITIES,
        re.compile(
            r"\b(what can (you|u) (do|help)|how can (you|u) help|"
            r"what do (you|u) do|how do (you|u) work|what can i ask|"
            r"help me|what should i ask|what are you for)\b"
        ),
    ),
    (
        Intent.THANKS,
        re.compile(
            r"\b(thank (you|u)|thanks|thankyou|thx|ty|appreciate it|cheers)\b"
        ),
    ),
    (
        Intent.GOODBYE,
        re.compile(
            r"\b(bye|goodbye|see (you|ya)|farewell|good night|gotta go|"
            r"talk later|catch you later)\b"
        ),
    ),
    (
        Intent.GREETING,
        re.compile(
            r"^(hi+|hey+|hello+|helo|yo|hiya|howdy|greetings|heya|"
            r"good (morning|afternoon|evening)|what'?s up|wassup|sup)\b"
        ),
    ),
]

# Guard: greeting/wellbeing/thanks/goodbye only count as small talk when the
# message is short. A long message that merely starts with "hi" is almost
# certainly a real question and should go to retrieval instead.
_MAX_CONVERSATIONAL_WORDS = 8
_SHORT_ONLY = {
    Intent.GREETING,
    Intent.WELLBEING,
    Intent.THANKS,
    Intent.GOODBYE,
}


def classify(message: str) -> Intent | None:
    """Classify ``message`` as a small-talk :class:`Intent`, or ``None``.

    ``None`` means "this isn't small talk — send it through the normal
    document-retrieval pipeline." The returned intent is a *hint* for the LLM
    that writes the reply; it does not itself contain any wording.
    """
    text = message.strip().lower()
    if not text:
        return None

    # Strip trailing punctuation so "hello!!!" / "thanks." still match.
    text = re.sub(r"[!?.…]+$", "", text).strip()

    for intent, pattern in _INTENT_PATTERNS:
        if pattern.search(text):
            if (
                intent in _SHORT_ONLY
                and len(text.split()) > _MAX_CONVERSATIONAL_WORDS
            ):
                continue
            return intent

    return None
