"""Question-answering service (orchestrates STEPs 5–7).

Retrieves context, generates a grounded answer, and returns citations. It adds
two defensive anti-hallucination layers on top of the prompt guardrail:

1. If retrieval returns nothing, we short-circuit to the refusal message and
   never call the LLM at all.
2. Citations are derived from the *retrieved* chunks, not parsed from free-form
   model output — so a source can never be fabricated. When the model returns
   the refusal message, we suppress citations entirely.
"""

from __future__ import annotations

import re

from app.core.exceptions import LLMError
from app.core.logger import get_logger
from app.rag import conversation
from app.rag.llm import LLMClient
from app.rag.prompt import NO_ANSWER_MESSAGE, REDIRECT_MESSAGE
from app.rag.retriever import Retriever
from app.schemas.api import Source
from app.schemas.documents import RetrievedChunk

logger = get_logger(__name__)

# Minimum similarity for a chunk to count as usable evidence. Chunks below this
# are treated as noise, guarding against confidently answering from weak matches.
_MIN_SCORE = 0.20

# Used only if the LLM small-talk call fails, so a greeting never hard-errors.
_CHAT_FALLBACK = (
    f"Hi! I'm {conversation.ASSISTANT_NAME}, your PhotonX assistant. "
    "Ask me anything about PhotonX's services, technology, team, or clients!"
)


class QAService:
    """Answer questions strictly from indexed PhotonX documentation."""

    def __init__(self, retriever: Retriever, llm: LLMClient) -> None:
        self._retriever = retriever
        self._llm = llm

    def ask(self, question: str) -> tuple[str, list[Source], str]:
        """Answer ``question`` and return ``(answer, sources, kind)``.

        ``kind`` is one of ``"chat"`` (small talk handled by the copilot
        persona), ``"answer"`` (a grounded answer with citations), or
        ``"redirect"`` (the question wasn't in the docs).
        """
        # 1) Copilot small talk (greetings, identity, thanks, …) is routed here
        #    before any retrieval. The reply is generated by the LLM so Buddy
        #    sounds natural and varied — the classifier only decides *that* it's
        #    small talk, not the wording.
        intent = conversation.classify(question)
        if intent is not None:
            logger.info("Conversational intent: %s", intent.value)
            try:
                reply = self._llm.chat(question, intent.value)
            except LLMError as exc:
                # A greeting should never hard-fail the turn; fall back to a
                # friendly static line if the chat call errors.
                logger.warning("Chat generation failed, using fallback: %s", exc)
                reply = _CHAT_FALLBACK
            return reply, [], "chat"

        # 2) Otherwise it's a documentation question: retrieve context.
        chunks = self._retriever.retrieve(question)
        relevant = [c for c in chunks if c.score >= _MIN_SCORE]

        if not relevant:
            logger.info("No sufficiently relevant context; redirecting.")
            return REDIRECT_MESSAGE, [], "redirect"

        answer = self._llm.generate(question, relevant)

        # If the model refused, deliver the warm redirect instead of the raw
        # refusal string, and attach no citations.
        if self._is_refusal(answer):
            return REDIRECT_MESSAGE, [], "redirect"

        cited = self._select_cited(answer, relevant)
        return answer, self._build_sources(cited), "answer"

    @staticmethod
    def _is_refusal(answer: str) -> bool:
        return NO_ANSWER_MESSAGE.lower() in answer.lower()

    @staticmethod
    def _select_cited(
        answer: str, chunks: list[RetrievedChunk]
    ) -> list[RetrievedChunk]:
        """Return only the chunks the answer actually cited via ``[n]`` markers.

        Chunks were presented to the model numbered ``[1]..[N]`` in the same
        order as ``chunks``. We map the markers back to those chunks so the
        returned sources reflect what the answer used — not every retrieved
        chunk. If the model cited nothing parseable, fall back to all chunks so
        an answer is never left source-less.
        """
        indices = {
            int(n)
            for n in re.findall(r"\[(\d{1,2})\]", answer)
            if 1 <= int(n) <= len(chunks)
        }
        if not indices:
            return chunks
        return [chunks[i - 1] for i in sorted(indices)]

    @staticmethod
    def _build_sources(chunks: list[RetrievedChunk]) -> list[Source]:
        """Deduplicate chunks into unique (document, page, section) citations."""
        seen: set[tuple[str, int, str]] = set()
        sources: list[Source] = []
        for chunk in chunks:
            key = (chunk.document, chunk.page, chunk.section)
            if key in seen:
                continue
            seen.add(key)
            sources.append(
                Source(
                    document=chunk.document,
                    page=chunk.page,
                    section=chunk.section,
                )
            )
        return sources
